### ISSUE TITLE
Better linking to Contributor Days page

### ISSUE THREAD

**Issue by taras** [this-dot/thisdot#51]
Currently, Contributor Days section on Media page only shows title for previous events. We want to make this area smarter.

<img width="1180" alt="screen shot 2017-02-13 at 12 46 52 pm" src="https://cloud.githubusercontent.com/assets/74687/22874235/f57c319c-f1ea-11e6-8381-ad5b34e7db91.png">

## TODO

- [x] Show data for all events (even
 past once)
- [x] Each Apply should link to it's corresponding Contributor Day page
- [x] For past events show "WATCH" button that links to Contributor Day page with video

**Comment by taras** [comment]
@zinyando I updated the issue to give you more information.
